backend:
  name: git-gateway
  branch: main

media_folder: "public/images/events"
public_folder: "/images/events"

collections:
  - name: "events"
    label: "Events"
    folder: "content/events"
    create: true
    slug: "{{slug}}"

    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Artist"
        name: "artist"
        widget: "string"

      - label: "Venue"
        name: "venue"
        widget: "string"

      - label: "Date"
        name: "date"
        widget: "datetime"

      - label: "Poster"
        name: "poster"
        widget: "image"

      - label: "Ticket Link"
        name: "ticket_link"
        widget: "string"
